### ISSUE TITLE
Not Registered Response from Autopush on v2

### ISSUE THREAD

**Issue by gauntface** [mozilla-services/autopush#644] opened 2016-09-01 16:21 UTC
I'm getting mixed results on this so please forgive the lack of information. 

I'm getting the impression that autopush v2 requires the VAPID headers or something has changed to make previously working samples to stop. Are there any major changes in the requirements for autopush v2 that you could share?

**Comment by kitcambridge** [comment] 2016-09-01 16:58
@gauntface Are you seeing that for Android subscriptions? /cc @jrconlin

**Comment by pinarx** [comment] 2016-09-02 11:20
For Desktop actually.

**Comment by jrconlin** [comment] 2016-09-02 15:33
@gauntface, @pinarx  Hmm, can you provide more details?

I have a test page that I use to check Push: https://mozilla-services.github.io/WebPushDataTestPage/

You shouldn't need to provide VAPID info.

If that doesn't work, can you provide:
the version of Firefox you're running, as well as what OS you're on, and the error message you're getting (or the point where things don't work). 
I may ask you to turn on debugging and open up the Browser Console.

Thanks!

**Comment by pinarx** [comment] 2016-09-02 15:59
I tried it on Firefox 48, stable on Mac. And today I got around it by providing the p256ecdsa in Crypto-Key header. (trial and error=)) No JWT though.

**Comment by kitcambridge** [comment] 2016-09-02 16:08
I'm so sorry, I misread the issue yesterday. When you created the subscription in the browser, did you pass an `applicationServerKey` option?

In theory, `/wpush/v2` means you have a restricted subscription, which should only allow pushes with a JWT signed with the matching private key. It sounds like we're not doing the check correctly, though, if it's allowing pushes with `Crypto-Key` but without a JWT.

**Comment by pinarx** [comment] 2016-09-02 16:35
So both of these curl requests work basically:

With Auth header:

curl "https://updates.push.services.mozilla.com/wpush/v2/gAAAAA..." --request POST --header "TTL: 60" --header "Content-Length: 0" --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.ey..." --header "Crypto-Key: p256ecdsa=BDd3_hVL..."

Without Auth header:

curl "https://updates.push.services.mozilla.com/wpush/v2/gAAAAA..." --request POST --header "TTL: 60" --header "Content-Length: 0" --header "Crypto-Key: p256ecdsa=BDd3_hVL..."

**Comment by jrconlin** [comment] 2016-09-02 16:42
I believe that this may be related to https://github.com/mozilla-services/autopush/issues/646. The server should reject v2 headers that do not specify the `p256ecdsa` element in the `Crypto-Key` header. The server is apparently failing to do that.

**Comment by jrconlin** [comment] 2016-09-02 16:45
I believe that this may be related to #646. The server should reject v2 headers that do not specify a valid `Authorization` header. The server is apparently failing to do that.

**Comment by pinarx** [comment] 2016-09-02 17:01
Seems so, the confusing part was that we were subscribing with an applicationServerKey all the time, and were getting v1 endpoint which worked fine without VAPID headers or the p256ecdsa key. Then at some point this week we started getting v2. Anyway #646 explains the issue I think.

**Comment by jrconlin** [comment] 2016-09-12 18:33
Closing as duplicate of #646

**Closed by jrconlin** 2016-09-12 18:33 UTC
