### ISSUE TITLE
Unhandled exception in GCM Routing: UUID('93606a29-75ab-41a7-867f-b78b937ff299') is not JSON serializable

### ISSUE THREAD

**Issue by goinnn** [mozilla-services/autopush#697] opened 2016-10-13 13:17 UTC
I get the next error when I send a push to my mobile browser (Firefox 49.0, platform Android):

    curl -v -isD -I -X POST  "https://updates.push.services.mozilla.com/wpush/gAAAAABX_3X5f_jqIEGJHq3ExVHzqEYLyTFBpLJ0IEXbc1i4-xbl-_dx0-D-MNdtNPjf919Zbvpvk6dbMj_cgBBilOTUTfdPSfz_j0So5m_OuJuYplQnUtb4yv7xh1Y2vMBaiqj6drxA" 

    HTTP/1.1 500 Internal Server Error

    {"errno": 999, "message": "Unhandled exception in GCM Routing: UUID('93606a29-75ab-41a7-867f-b78b937ff299') is not JSON serializable", "code": 500, "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "error": "Internal Server Error"}

But this works if I send a push to my desktop browser (Firefox 49.0.1, platform Ubuntu), this works without problems:

    curl -v -isD -I -X POST  "https://updates.push.services.mozilla.com/wpush/gAAAAABX_3ZeATsvMqCREwfOOT42NhadTPA4YjGvSb6P3YhdofGoeqE5MgwgZEvgFHLywNkBw8wZ3lk9F7z0G7k5JE5_H7v6eqe1Dp67p2HBxj1r4rKJP2z3L78stzSrzcqMeo9cI-Ng" 

    HTTP/1.1 201 Created

This is the complete error trace:

    curl -v -isD -I -X POST  "https://updates.push.services.mozilla.com/wpush/gAAAAABX_3X5f_jqIEGJHq3ExVHzqEYLyTFBpLJ0IEXbc1i4-xbl-_dx0-D-MNdtNPjf919Zbvpvk6dbMj_cgBBilOTUTfdPSfz_j0So5m_OuJuYplQnUtb4yv7xh1Y2vMBaiqj6drxA" 
    * Hostname was NOT found in DNS cache
    *   Trying 52.37.242.249...
    * Connected to updates.push.services.mozilla.com (52.37.242.249) port 443 (#0)
    * successfully set certificate verify locations:
    *   CAfile: none
    CApath: /etc/ssl/certs
    * SSLv3, TLS handshake, Client hello (1):
    * SSLv3, TLS handshake, Server hello (2):
    * SSLv3, TLS handshake, CERT (11):
    * SSLv3, TLS handshake, Server key exchange (12):
    * SSLv3, TLS handshake, Server finished (14):
    * SSLv3, TLS handshake, Client key exchange (16):
    * SSLv3, TLS change cipher, Client hello (1):
    * SSLv3, TLS handshake, Finished (20):
    * SSLv3, TLS change cipher, Client hello (1):
    * SSLv3, TLS handshake, Finished (20):
    * SSL connection using ECDHE-RSA-AES128-GCM-SHA256
    * Server certificate:
    *        subject: C=US; ST=California; L=Mountain View; O=Mozilla Corporation; CN=push.services.mozilla.com
    *        start date: 2016-01-08 00:00:00 GMT
    *        expire date: 2019-01-16 12:00:00 GMT
    *        subjectAltName: updates.push.services.mozilla.com matched
    *        issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
    *        SSL certificate verify ok.
    > POST /wpush/gAAAAABX_3X5f_jqIEGJHq3ExVHzqEYLyTFBpLJ0IEXbc1i4-xbl-_dx0-D-MNdtNPjf919Zbvpvk6dbMj_cgBBilOTUTfdPSfz_j0So5m_OuJuYplQnUtb4yv7xh1Y2vMBaiqj6drxA HTTP/1.1
    > User-Agent: curl/7.35.0
    > Host: updates.push.services.mozilla.com
    > Accept: */*
    > 
    < HTTP/1.1 500 Internal Server Error
    HTTP/1.1 500 Internal Server Error
    < Access-Control-Allow-Headers: content-encoding,encryption,crypto-key,ttl,encryption-key,content-type,authorization
    Access-Control-Allow-Headers: content-encoding,encryption,crypto-key,ttl,encryption-key,content-type,authorization
    < Access-Control-Allow-Methods: POST
    Access-Control-Allow-Methods: POST
    < Access-Control-Allow-Origin: *
    Access-Control-Allow-Origin: *
    < Access-Control-Expose-Headers: location,www-authenticate
    Access-Control-Expose-Headers: location,www-authenticate
    < Content-Type: application/json
    Content-Type: application/json
    < Date: Thu, 13 Oct 2016 13:12:17 GMT
    Date: Thu, 13 Oct 2016 13:12:17 GMT
    * Server cyclone/1.1 is not blacklisted
    < Server: cyclone/1.1
    Server: cyclone/1.1
    < Content-Length: 260
    Content-Length: 260
    < Connection: keep-alive
    Connection: keep-alive

    < 
    * Connection #0 to host updates.push.services.mozilla.com left intact
    {"errno": 999, "message": "Unhandled exception in GCM Routing: UUID('93606a29-75ab-41a7-867f-b78b937ff299') is not JSON serializable", "code": 500, "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "error": "Internal Server Error"}

I am not sure if this is a bug or I have change something in my call. But at least this should return a know error, something different to 500 and errno 999 - Unknown error.

I think the errors is produced here:

https://github.com/mozilla-services/autopush/blob/master/autopush/router/gcm.py#L114

Thanks!!

**Comment by jrconlin** [comment] 2016-10-13 14:54
Duplicate of #692

**Closed by jrconlin** 2016-10-13 14:54 UTC
