### ISSUE TITLE
client supplied chids to registration should be forced to hex format

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#710] opened 2016-10-14 20:53 UTC
RegistrationHandler post allows a client supplied chid. It either shouldn't at all or should at least be standardized to hex after validation.

It currently allows any form accepted by python's UUID() which is too lenient.

**Comment by jrconlin** [comment] 2016-11-16 21:58
I believe the problem is that the client is responsible for the channelid generation. 
https://dxr.mozilla.org/mozilla-central/source/dom/push/PushServiceWebSocket.jsm#785

The server can't alter the string provided since clients can use that string as a map key. The server could reject "poorly formatted" channelIDs from the client, but we'd run the risk of breaking non-conformant clients that may already exist (which is probably "all of them" at this point). 

Added fun fact: `Cc["@mozilla.org/uuid-generator;1"].getService(Ci.nsIUUIDGenerator).generateUUID().number` produces the string `"{2efbf342-65fe-44fd-86f7-138f88825e29}"`
The code above strips the curly braces.

There does not appear to be a native UUID manipulation functions available, [only generation](https://dxr.mozilla.org/mozilla-central/source/obj-x86_64-pc-linux-gnu/dist/include).

**Comment by jrconlin** [comment] 2017-04-19 18:32
I'm tempted to mark this as "WONTFIX". This is dependent on client behaviors.

**Comment by jrconlin** [comment] 2017-05-31 18:23
INVALID: 
Overcome by events via refactors.

**Closed by jrconlin** 2017-05-31 18:23 UTC
Labels: blocked, p3
