### ISSUE TITLE
Error 106 or 103 stops delivery of notifications to valid destinations

### ISSUE THREAD

**Issue by neekrish** [mozilla-services/autopush#1099] opened 2017-12-15 18:50 UTC
I'm using a Apache HTTP client (in java) to connect to firefox/chrome webpush server. Everything works fine until a these errors come:
'{"code": 410, "errno": 106, "error": "", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate No such subscription"}'

'{"code": 410, "errno": 103, "error": "", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate UAID not found"}'

Soon after this, most worrying part is other users who have valid registrations don't receive the notifications although the server responds with a 200 OK.

Once the server that connects to autopush is restarted, everything starts to work again until another 106 or 103 error happens.

Any suggestions to resolve this or atleast avoid getting into this situation?

**Comment by pjenvey** [comment] 2018-01-16 23:51
We are not able to reproduce this, is this still an issue? If so, can you please give us step-by-step instructions on how to reproduce it?

**Comment by bbangert** [comment] 2018-03-26 16:06
Closing this as no further feedback has occurred.

**Closed by bbangert** 2018-03-26 16:06 UTC
Labels: blocked
