### ISSUE TITLE
Move preflight check for webpush into validation.py

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#563] opened 2016-07-28 18:24 UTC
Once #492 is complete, then the preflight check from router/webpush.py should be moved into the WebPushRequest schema in validation.py.

**Comment by bbangert** [comment] 2016-07-28 18:25
Blocked on #492.

**Comment by jrconlin** [comment] 2016-08-19 17:28
crap, restoring because of blockage.

**Comment by pjenvey** [comment] 2017-01-11 01:03
#765 was a duplicate of this -- now fixed as of PR #772

**Closed** 2017-01-11 01:03 UTC
Labels: blocked, enhancement, p3
